addons:
  sonarcloud:
    organization: "dipkiran"
    token:
      secure: "b1Jbs431XlZslZDUeNI9TX0Wb0rlZIygqiaXwgweurb9xW+4F7pzVYUYrIOvl+7kwKcLSw30+Et5aqLRNEWwjgAYv7YwSrB2hJZCAbO+cxxRp84y1WJOviQQCfB+w6yQHSP9/pI51zaU9Jsfdg3GNr931IlmiIKupbeGpk21hq+o9FpeISdJFzQXHCs2z812BUnj5jzkWnN/MrPH7e6gTa/aJ+U0HSZyQPvoOgZ2cKiE4NdzsVWEJuO4BYWS4hPIEB6LDbNbVdpyY3ac/eeDeG1JNEfXYxl0Ek1CCDuenL1+aWwZEFnEyVLxSgrUMTINvAdbdv1w1TB9CY26UtF9pswjilp7MskOCdXgaJ2Gf1SuXsaKlTN98rLWmvMLjDW97FHNQ6dPUukEq45ZHwHozLj2n5uo++BizJ1jFZWu7nBTO5uc/s1UxWf7xmKv7UmzQ+8ItHlywduSKVCO+df/BYbvFuMbDSjWXLjoD9bKdGaqOcKgv0ITlForveU91pRqhEK1tYutA92MOHQHNMaMxf7XQ9HqCZz5NcHYJ23QXM6gNBTcS0n5K9stTNtq6u15Em/RJnAU7qYLEUVstHNZ+OMq163+Zq0gXPqt6i8z6AoylpAKdvIoAscLX2JkzVRmbWHevGwZGzNN5Mgvo39iboLDEjiaB7y+6VImj4S2OMc=" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output <insert_your_clean_build_command>
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
